
export enum OccupationSection {
    Leader = "Leader",
    Collaborators = "Collaborators",
    HDRStudents = "HDRStudents",
    HonorsStudent = "HonorsStudent",
}


export interface MemberOutputDto {
    id: string;
    name: string;
    occupation: OccupationSection;
    profileImage?: string;
    occupationSub?: string;
    orderNumber: number;
    email?: string;
    linkedIn?: string;
    homepage?: string;
    github?: string;
    scholar?: string;
}


export const allMembers: MemberOutputDto[] = [
    {
        id: "1",
        name: "Dr. Chun Ouyang",
        occupation: OccupationSection.Leader,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1620301124/rhju6s6uoldcnxmw7c0o.jpg",
        occupationSub: "Senior Lecturer",
        orderNumber: 1,
        email: "c.ouyang@qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/chunouyang",
        homepage: "https://www.qut.edu.au/about/our-people/academic-profiles/c.ouyang",
        github: "",
        scholar: "https://scholar.google.com.au/citations?user=aQqD_CQAAAAJ",
    },
    {
        id: "2",
        name: "Dr. Catarina Moreira",
        occupation: OccupationSection.Leader,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619535125/vtyukjmxpoy2afzfpzfj.png",
        occupationSub: "Lecturer in Information Science",
        orderNumber: 2,
        email: "catarina.pintomoreira@qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/catarinapmoreira",
        homepage: "https://cmoreira.eu",
        github: "",
        scholar: "https://scholar.google.com/citations?user=nThsEsMAAAAJ",
    },
    {
        id: "3",
        name: "Dr. Renuka Sindhgatta",
        occupation: OccupationSection.Collaborators,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1621573588/begjin9xq99zcs3m89je.jpg",
        occupationSub: "IBM Research",
        orderNumber: 1,
        email: "renuka.sr@ibm.com",
        scholar: "https://scholar.google.com/citations?user=P-YUol0AAAAJ",
        linkedIn: "https://www.linkedin.com/in/renuka-sindhgatta-9042242",
        github: "",
    },
    {
        id: "4",
        name: "A\Prof. Yue Xu",
        occupation: OccupationSection.Collaborators,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1621573622/israd7mxvdxd5gbljesp.jpg",
        occupationSub: "Associate Professor",
        orderNumber: 2,
        email: "yue.xu@qut.edu.au",
        homepage: "https://www.qut.edu.au/about/our-people/academic-profiles/yue.xu",
        scholar: "https://scholar.google.com/citations?user=dGr7W1kAAAAJ",
        linkedIn: "https://www.linkedin.com/in/yue-xu-7368b133"
    },
    {
        id: "5",
        name: "Prof. Joaquim Jorge",
        occupation: OccupationSection.Collaborators,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619535448/jvdkcyvgrqu5foyvxpd2.jpg",
        occupationSub: "Professor at Instituto Superior Técnico",
        orderNumber: 3,
        email: "jorgej©tecnico.ulisboa.pt",
        homepage: "https://web.ist.utl.pt/jorgej/",
        scholar: "https://scholar.google.com/citations?user=RgiMdpAAAAAJ",
        linkedIn: "https://www.linkedin.com/in/jorgej",
    },
    // {
    //     id: "6",
    //     name: "Prof. Will van der Aalst",
    //     occupation: OccupationSection.Collaborators,
    //     profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619535518/knaomursmwrmfqp4aiwj.jpg",
    //     occupationSub: "",
    //     orderNumber: 3,
    // },
    {
        id: "7",
        name: "Mythreyi Velmurugan",
        occupation: OccupationSection.HDRStudents,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619535615/v2pxj7ommlm6a4uccuhp.jpg",
        occupationSub: "PhD Student",
        orderNumber: 2,
        email: "mythreyi.velmurugan@hdr.qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/mythreyivelmurugan",
        scholar: "https://scholar.google.com/citations?user=MfkWJ84AAAAJ",
        homepage: "",
        github: "",
    },
    {
        id: "8",
        name: "Yu-Liang (Leon) Chou",
        occupation: OccupationSection.HDRStudents,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619535686/lolnxfe64mt8vydthdlk.jpg",
        occupationSub: "PhD Student",
        orderNumber: 3,
        email: "yuliang.chou@hdr.qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/leon-chou-3b56ba175",
        scholar: "",
        homepage: "",
        github: "",
    },
    {
        id: "9",
        name: "Peng (Kenny) Yu",
        occupation: OccupationSection.HDRStudents,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619535769/cbyv9gnmzbzlc5hmoc3s.jpg",
        occupationSub: "PhD Student",
        orderNumber: 4,
        email: "p6.yu@hdr.qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/kenny-yu-b82373130",
        scholar: "",
        homepage: "",
        github: "",
    },
    {
        id: "10",
        name: "Bemali Wickramanayake",
        occupation: OccupationSection.HDRStudents,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619535852/efc2p3t0h1soojoksmdi.png",
        occupationSub: "PhD Student",
        orderNumber: 5,
        email: "bemali.wickramanayake@hdr.qut.edu.au",
        linkedIn: "",
        scholar: "",
        homepage: "",
        github: "",
    },
    {
        id: "11",
        name: "Jia (Jenny) Wei",
        occupation: OccupationSection.HDRStudents,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1620277624/rx31uwskj5lh26vpf8ws.jpg",
        occupationSub: "PhD Student",
        orderNumber: 6,
        email: "jia.wei@hdr.qut.edu.au",
        linkedIn: "",
        scholar: "",
        homepage: "",
        github: "",
    },
    {
        id: "12",
        name: "Chihcheng (Richard) Hsieh",
        occupation: OccupationSection.HDRStudents,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1619954466/frip22rpmow3rmas33lg.jpg",
        occupationSub: "Research Assistant",
        orderNumber: 7,
        email: "c21.hsieh@qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/chihcheng-hsieh-04623989",
        scholar: "",
        homepage: "",
        github: "https://github.com/ChihchengHsieh",
    },
    {
        id: "13",
        name: "Zhipeng (Zippo) He",
        occupation: OccupationSection.HDRStudents,
        profileImage: "https://res.cloudinary.com/dcd56w8gc/image/upload/v1621732433/hb4j78tkbsewdqnhdvzw.jpg",
        occupationSub: "Honours Student",
        orderNumber: 8,
        email: "zhipeng.he@connect.qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/zhipenghe",
        homepage: "https://zhipenghe.me",
        github: "https://github.com/ZhipengHe",
        scholar: "",
    },
    {
        id: "14",
        name: "Jing (Roy) Yang",
        occupation: OccupationSection.HDRStudents,
        // TODO: change the link of roy's profile pic
        profileImage: "",
        occupationSub: "PhD Student",
        orderNumber: 1,
        email: "roy.j.yang@qut.edu.au",
        linkedIn: "https://www.linkedin.com/in/roy-jingyang",
        scholar: "https://scholar.google.com/citations?user=Ms1FNhsAAAAJ",
        homepage: "https://royjy.me/",
        github: "https://github.com/roy-jingyang",
    }
];
